# Generated by Django 5.1 on 2024-09-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('number', models.CharField( max_length=20)),
                ('tc', models.CharField( max_length=11)),
                ('mail', models.EmailField( max_length=100)),
                ('phone', models.CharField( max_length=11)),
                ('birthDate', models.DateField()),
                ('address', models.CharField( max_length=250)),
                ('school', models.CharField( max_length=50)),
                ('department', models.CharField( max_length=50)),
                ('stu_class', models.CharField( max_length=10)),
                ('graduate_year', models.IntegerField()),
            ],
        ),
    ]
