# Generated by Django 5.1 on 2024-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
