# Generated by Django 5.1 on 2024-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_alter_students_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='graduate_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
