# Generated by Django 5.1 on 2024-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_alter_students_graduate_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='students',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='graduate_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_class',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='tc',
            field=models.CharField(max_length=11),
        ),
    ]
