# Generated by Django 5.1 on 2024-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_alter_students_address_alter_students_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='graduate_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_class',
            field=models.CharField(max_length=10),
        ),
    ]
