# Generated by Django 5.1 on 2024-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0005_alter_students_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='tc',
            field=models.IntegerField(),
        ),
    ]
