# Generated by Django 5.1 on 2024-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0006_alter_students_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='tc',
            field=models.CharField(max_length=11),
        ),
    ]
